version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-network  # Use the network if created

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "10.5.4.43:9092:9092"  # Update the host IP here
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.5.4.43  # Update the host IP here
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka-network  # Use the network if created
    volumes:
      - ./python:/python  # Mount the local 'python' directory into the container

networks:
  kafka-network:
    driver: bridge
